# Generated by Django 3.1.4 on 2020-12-09 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('python_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cre_date',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 4, 16, 37, 816724, tzinfo=utc), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date'),
        ),
    ]
